apiVersion: batch/v1
kind: CronJob
metadata:
  name: calibration-scheduler
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: digilog-calibration-scheduler
              resources:
                limits:
                  cpu: 250m
                  memory: 256Mi
                requests:
                  cpu: 250m
                  memory: 256Mi