apiVersion: batch/v1
kind: CronJob
metadata:
  name: url-checker
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: digilog-url-checker
              resources:
                limits:
                  cpu: 250m
                  memory: 256Mi
                requests:
                  cpu: 250m
                  memory: 256Mi