apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - postgres-pvc.yaml
  - mongodb-pvc.yaml
  - loki-pvc.yaml
  - grafana-pvc.yaml
  - flyway-job.yaml
  - postgres-sts.yaml
  - mongodb-sts.yaml
  - scrapy-deployment.yaml
  - web-deployment.yaml
  - loki-sts.yaml
  - grafana-sts.yaml
  - scheduler-test-job.yaml
  - cj-url-checker.yaml
  - cj-calibration-scheduler.yaml
  - cj-calibration-analyser.yaml
  - cj-crawl-scheduler.yaml

patches:
  - target:
      kind: Ingress
      name: ingress
    path: ingress-patch.json
