apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - postgres-pvc.yaml
  - mongodb-pvc.yaml
  - flyway-job.yaml
  - postgres-deployment.yaml
  - mongodb-deployment.yaml
  - scrapy-deployment.yaml
  - web-deployment.yaml

patches:
  - target:
      kind: Ingress
      name: web-ingress
    path: web-ingress-patch.json
