apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - postgres-deployment.yaml
  - postgres-pvc.yaml
  - postgres-service.yaml
  - postgres-cm.yaml
  - flyway-job.yaml
