apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  template:
    spec:
      containers:
      - name: digilog-mongodb
        resources:
          limits:
            cpu: 1
            memory: 3Gi
          requests:
            cpu: 1
            memory: 3Gi
