apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: digilog
    run: postgres
    tier: storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: csi-cinder-sc-delete
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: digilog
    run: postgres
    tier: storage
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digilog
      run: postgres
      tier: storage
  template:
    metadata:
      labels:
        app: digilog
        run: postgres
        tier: storage
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pg-secret
              optional: false
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: pg-secret
              optional: false
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: databaseName
              name: pg-config
              optional: false
        image: postgres:13.0
        name: digilog-postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migrate
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: flyway-migrate
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pg-secret
              optional: false
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: pg-secret
              optional: false
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: databaseName
              name: pg-config
              optional: false
        image: trephor/digilog-flyway
        name: digilog-flyway
      restartPolicy: OnFailure
