apiVersion: batch/v1
kind: Job
metadata:
  name: scheduler-test
spec:
  template:
    spec:
      containers:
        - name: digilog-scheduler
          args: ["/usr/src/scheduler.py", "calibrate", "municipality", "-84"]
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi