apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapy
spec:
  template:
    spec:
      containers:
        - name: digilog-scrapy
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 2Gi
