apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapy
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: digilog-scrapy
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
        - name: scrapy-fluentd
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
