apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - pv-1.yaml
  - pv-2.yaml
  - pv-3.yaml
  - postgres-secret.yaml
  - mongodb-secret.yaml
patchesStrategicMerge:
  - postgres-pvc.yaml
  - mongodb-pvc.yaml
  - loki-pvc.yaml
