apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc 
spec:
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      type: local
      run: loki
  storageClassName: slow
