apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
  labels:
    type: local
    run: postgres
spec:
  storageClassName: slow
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv-1"
