apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-3
  labels:
    type: local
    run: mongodb
spec:
  storageClassName: slow
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv-3"
