apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-4
  labels:
    type: local
    run: grafana
spec:
  storageClassName: slow
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv-4"
