apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migrate
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: flyway-migrate
    spec:
      containers:
        - name: digilog-flyway
          image: trephor/digilog-flyway:0.1
          imagePullPolicy: Always
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
                  optional: false
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: user
                  optional: false
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-cm
                  key: databaseName
                  optional: false
      restartPolicy: OnFailure
