apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migrate
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: flyway-migrate
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-secret
              optional: false
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: postgres-secret
              optional: false
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: databaseName
              name: postgres-cm
              optional: false
        image: trephor/digilog-flyway:0.1.9
        name: digilog-flyway
      restartPolicy: OnFailure
