apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: digilog
    tier: logging
    run: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digilog
      tier: logging
      run: grafana
  template:
    metadata:
      labels:
        app: digilog
        tier: logging
        run: grafana
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          securityContext:
            privileged: true
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
          command:
            - sh
            - -c
            - >-
              id;
              ls -la /var/lib/grafana;
              mkdir -p /var/lib/grafana;
              chown 472:472 /var/lib/grafana;
              ls -la /var/lib/grafana;
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-vol
              subPath: grafana
      containers:
        - name: digilog-grafana
          image: grafana/grafana:8.5.2
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-vol
              subPath: grafana
      volumes:
        - name: grafana-vol
          persistentVolumeClaim:
            claimName: grafana-pvc
