apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: digilog
    tier: logging
    run: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digilog
      tier: logging
      run: loki
  template:
    metadata:
      labels:
        app: digilog
        tier: logging
        run: loki
    spec:
      containers:
      - name: digilog-loki
        image: grafana/loki:2.4.2
        ports:
        - containerPort: 3100
        volumeMounts:
          - mountPath: /loki
            name: loki-vol
            subPath: loki
      volumes:
        - name: loki-vol
          persistentVolumeClaim:
            claimName: loki-pvc
