apiVersion: batch/v1
kind: Job
metadata:
  name: scheduler-test
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: scheduler-test
    spec:
      containers:
      - args:
        - /usr/src/scheduler.py
        - calibrate
        - municipality
        - '-84'
        command:
        - /usr/venv/bin/python
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-secret
              optional: false
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: postgres-secret
              optional: false
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: databaseName
              name: postgres-cm
              optional: false
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mongodb-secret
              optional: false
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: mongodb-secret
              optional: false
        - name: SCHEDULER_LOGGING_TARGET
          value: LOKI
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: trephor/digilog-scheduler:0.2.0
        name: digilog-scheduler
      restartPolicy: OnFailure
