apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-fluent-cm
data:
  fluent.conf: |
    <source>
      @type tail
      path "/var/log/scheduler/scheduler.log"
      pos_file /var/log/scheduler/scheduler.pos
      format /^(?<time>[^\[]+) (?<level>[^:]+) \[(?<logger>[^\[]+)\] (?<message>.*)$/
      time_format %Y-%m-%d %H:%M:%S,%N
      tag scheduler
    </source>

    <match scheduler>
      @type loki
      url "#{ENV['LOKI_URL']}"
      extra_labels {"component":"scheduler"}
      flush_interval 10s
      flush_at_shutdown true
      buffer_chunk_limit 1m
    </match>

