apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapy
  labels:
    app: digilog
    tier: crawling
    run: scrapy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digilog
      tier: crawling
      run: scrapy
  template:
    metadata:
      labels:
        app: digilog
        tier: crawling
        run: scrapy
    spec:
      containers:
      - name: digilog-scrapy
        image: trephor/digilog-scrapy
        command: ["python"]
        args: ["/src/queue_processor.py"]
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
              optional: false
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: user
              optional: false
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-cm
              key: databaseName
              optional: false
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
              optional: false
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: user
              optional: false
