apiVersion: v1
kind: ConfigMap
metadata:
  name: web-fluent-cm
data:
  fluent.conf: |
    <source>
      @type tail
      path "/var/log/gunicorn/access.log"
      pos_file /var/log/gunicorn/access.pos
      format apache2
      tag web.access-logs
    </source>
    <match web.access-logs>
      @type loki
      url "#{ENV['LOKI_URL']}"
      flush_interval 10s
      flush_at_shutdown true
      buffer_chunk_limit 1m
    </match>

