apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: digilog
    run: web
    tier: frontend
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digilog
      run: web
      tier: frontend
  template:
    metadata:
      labels:
        app: digilog
        run: web
        tier: frontend
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-secret
              optional: false
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: postgres-secret
              optional: false
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: databaseName
              name: postgres-cm
              optional: false
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mongodb-secret
              optional: false
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: mongodb-secret
              optional: false
        image: trephor/digilog-web:0.1.7
        name: digilog-web
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /etc/config
          name: gunicorn-conf
        - mountPath: /var/log/gunicorn
          name: gunicorn-logs
      - env:
        - name: LOKI_URL
          value: http://$(LOKI_SERVICE_HOST):$(LOKI_SERVICE_PORT)
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: grafana/fluent-plugin-loki:main-d320873-amd64
        name: web-fluentd
        volumeMounts:
        - mountPath: /var/log/gunicorn
          name: gunicorn-logs
        - mountPath: /fluentd/etc
          name: fluentd-conf
      volumes:
      - configMap:
          name: gunicorn-cm
        name: gunicorn-conf
      - emptyDir: {}
        name: gunicorn-logs
      - configMap:
          name: web-fluent-cm
        name: fluentd-conf
