apiVersion: v1
kind: ConfigMap
metadata:
  name: web-fluent-cm
data:
  fluent.conf: |
    <source>
      @type tail
      path "/var/log/gunicorn/access.log"
      pos_file /var/log/gunicorn/access.pos
      format apache2
      tag web.access-logs
    </source>
    <filter web.access-logs>
      @type record_transformer
      <record>
        tag ${tag}
      </record>
    </filter>
    <match web.access-logs>
      @type loki
      url "#{ENV['LOKI_URL']}"
      extra_labels "{\"component\": \"web\", \"pod\": \"#{ENV['POD_NAME']}\"}"
      flush_interval 10s
      flush_at_shutdown true
      buffer_chunk_limit 1m
    </match>

