apiVersion: v1
kind: ConfigMap
metadata:
  name: web-fluent-cm
data:
  fluentd.conf: |
    <source>
      @type tail
      path "/var/log/#{ENV['POD_NAMESPACE']}_#{ENV['POD_NAME']}_#{ENV['POD_UID']}/#{ENV['CONTAINER_NAME']}/*"
      pos_file /etc/log.pos
      format apache2
      tag web.access-logs
    </source>
    <match web.access-logs>
      @type loki
      url "#{ENV['LOKI_URL']}"
      flush_interval 10s
      flush_at_shutdown true
      buffer_chunk_limit 1m
    </match>

