apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: digilog
    tier: frontend
    run: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digilog
      tier: frontend
      run: web
  template:
    metadata:
      labels:
        app: digilog
        tier: frontend
        run: web
    spec:
      containers:
      - name: digilog-web
        image: trephor/digilog-web
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
              optional: false
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: user
              optional: false
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-cm
              key: databaseName
              optional: false
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
              optional: false
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: user
              optional: false
        ports:
        - containerPort: 5000
      - name: web-fluentd
        image: grafana/fluent-plugin-loki:main-d320873-amd64
        env:
          - name: LOKI_URL
            value: 'http://loki-service:3100'
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          - name: CONTAINER_NAME
            value: digilog-fluentd
        volumeMounts:
          - mountPath: /var/log
            name: logs
      volumes:
        - name: logs
          hostPath:
            path: /var/log/pods/
            type: Directory

